### ISSUE TITLE
Registration and Eligibility rework

### ISSUE THREAD

**Issue by zkysar** [cpp-coding-challenge/cpp-coding-challenge.github.io#5]
@sunyu912 Do we want these two be in two separate sections? Right now it looks like it needs some work.

**Comment by sunyu912** [comment]
I put them together because they don't have much text and the two sections will look too lonely. If you have some good style to handle this, that would be great. Either is fine with me.

**Comment by Cnibungco** [comment]
Suggestion: Eligibility could go under the Rules Section

**Comment by sunyu912** [comment]
I am just going to highlight the eligibility, so that they can see it clearly and know that they are eligible. The first item in the Rules says it, too. 

For this section, I think we just need to adjust the margin between eligibility and registration, as well as the margin between the registration text and a button.

**Comment by Cnibungco** [comment]
We already mention Eligibility in the Rules, so I'm just going to remove it.
